#
# THIS SETS UP THE ENVIRONMENT VARIABLES TO RUN THE PROGRAM
# IT'S ALL UPPERCASE BECAUSE ... DOS.
#
# COPY THIS FILE INTO THE SAME DIRECTORY AS THE importer-1.0-SNAPSHOT.jar FILE
#
# EDIT THIS FILE TO THE CORRECT VALUES FOR YOUR ENVIRONMENT
# IF YOU ARE USING INTEGRAGED SECURITY ON WINDOWS USE EMPTY STRINGS WITH
# THE USERNAME AND PASSWORD
#

SET SPRING_DATASOURCE_URL=[fill in with your enviornment's URL]
SET SPRING_DATASORUCE_USERNAME=[fill in with your env's username or ""]
SET SPRING_DATASOURCE_PASSWORD=[fill in with your env's password or ""]

SET ML_HOST=127.0.0.1
SET ML_USERNAME=[MarkLogic user]
SET ML_PASSWORD=[MarkLogic password]

java -classpath misc -jar importer-1.0-SNAPSHOT.jar